# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute C-score window values (Optimized)
#' 
#' @param count Vector of counts
#' @param flanking Size of the flanking window
#' @param method "mean" or "median"
#' @return Vector of flanking values (same length as count)
#' @export
compute_window_score_cpp <- function(count, flanking, method) {
    .Call('_rRMSAnalyzer_compute_window_score_cpp', PACKAGE = 'rRMSAnalyzer', count, flanking, method)
}

